name: minio_new
description: Unofficial MinIO Dart Client SDK that provides simple APIs to access any Amazon S3 compatible object storage server.
version: 1.0.2
homepage: https://github.com/xtyxtyx/minio-dart
issue_tracker: https://github.com/xtyxtyx/minio-dart/issues

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  meta: ^1.8.0
  http: ^0.13.5
  crypto: ^3.0.2
  convert: ^3.1.1
  xml: ^6.1.0
  buffer: ^1.1.1
  intl: ^0.18.0
  mime: ^1.0.2
  path: ^1.8.2

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.8
  html: ^0.15.0
